# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
#        node-version: [14.x, 16.x, 18.x]
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"
        echo "GITHUB_REF=$GITHUB_REF"
        echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
        echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
        echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER"
        echo "GITHUB_SHA=$GITHUB_SHA"
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
        echo "this workflow was triggered by: $GITHUB_ACTOR"
        echo "this workflow was triggered by this event: $GITHUB_EVENT_NAME"
        echo "the event payload is:"
        cat $GITHUB_EVENT_PATH
    - name: condition 1
      if: runner.os == 'Windows'
      run: echo "The operating system on the runner is $env:RUNNER_OS."
    - name: condition 2
      if: runner.os != 'Windows'
      run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
